name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Get tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

    - name: Generate release notes
      run: awk 'BEGIN { RS="# "; FS="\n"; OFS=""; ORS="" } NR == 2 { print "# Changes in ", $0 }' < CHANGELOG.md > RELEASE.md

    - name: Build artifacts
      run: |
        go version
        go install github.com/mitchellh/gox@latest
        export version=${{ steps.tag.outputs.tag }}
        make cross
        mv dist/darwin_arm64_voormedia-toolkit dist/darwin_arm64_vmt
        mv dist/darwin_amd64_voormedia-toolkit dist/darwin_amd64_vmt
        mv dist/linux_amd64_voormedia-toolkit dist/linux_amd64_vmt

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.md
        name: ${{ github.ref_name }}
        files: |
          dist/darwin_arm64_vmt
          dist/darwin_amd64_vmt
          dist/linux_amd64_vmt
