name: Test & lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Run vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...
