name: Test & lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: "1.18"

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Run tests
      run: go test -v ./...
